language: node_js
node_js:
- '6.10'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: jnmiller@cryptofreak.org
  api_key:
    secure: GMOrllhu0wOzXwWgoj9cH3C+bM6eUzEuxnIH5RfUHgZXf5g7NCD48hM0TdqH5kqDwN5S69QcbV4QFWCTSHc99uiiw636vBLw8SMd9t6PyKAmcwHZLTE2vrnF1JcwBQ2TKTLCw1uRDFS3aWvLl9kvVk9Mqq1xwoGV+8S3WJKDGQh23OQsHrJDIeIek7kUppBRxEZdpgRQFmUAtB/izhz/XI7rzoxvA8IIqEukB0iXJEZWQIoFEnHZcSeh/t4EizZ1eCgNzFgt5jGZOu0T9cguyfTfl2w+ThFSNPOEzFryGcbBlOXGMI6uqbWV2XWKnqc/92nfgbzkytOo6RAE2k9d2ubmOSmhsq2r9LlMvgaX8yyQWkzkmgw47CGuXLID4O5EUNlzJDwKOtbya7yFbR7oPhNd+ufe0azMoO8xYpBI+MaU7FIeaQBQl+9c0owgA6hvOO0FQrxsm0YPOKDkb/vO0CFRNECuyXvgg2UzJk7lfkkW9RPlM2clRV+L1ncor3PzuEseuW6NLDzyO2P9WRzQxN4bw+qeXFX+K3Oiv8h3CHo51RdJZVprZ+Wt5kz2UVgiqK5oWcWaE8ZgTY81a7Xs4ZAE4rXED7ApzYbyouh2OLR85tjlvEHKbVQZoaO8ywX2OGmtc7ZhkHnScLlPKbXhDWUgjytyCaSQqlsk3+xM9Xo=
  on:
    tags: true
    repo: ladenedge/textanalytics-botframework-middleware
